version: '3.4'

services:
  worker: &netbox
    build:
      context: ../
      dockerfile: ./development/Dockerfile
      args:
        NETBOX_VERSION: ${NETBOX_VERSION-develop}
    command: sh -c "python manage.py rqworker"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./configuration.py:/opt/netbox/netbox/netbox/configuration.py
      - ../netbox_config_diff:/plugin/netbox_config_diff/netbox_config_diff
      - ../tests:/plugin/netbox_config_diff/tests

  netbox:
    <<: *netbox
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - worker
      - redis

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=netbox
      - POSTGRES_USER=netbox
      - POSTGRES_PASSWORD=netbox
    volumes:
      - pgdata-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: sh -c "redis-server --appendonly yes --requirepass redis"
    volumes:
      - redis-data:/data

volumes:
  pgdata-data:
    driver: local
  redis-data:
    driver: local
