import importlib.util
import sys
from pathlib import Path

import pytest

# Import sros module directly to avoid triggering netbox_config_diff.__init__
# which requires Django/NetBox
_sros_path = Path(__file__).parent.parent / "netbox_config_diff" / "compliance" / "sros.py"
_spec = importlib.util.spec_from_file_location("sros", _sros_path)
sros = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(sros)

_braces_to_indented = sros._braces_to_indented
_indented_to_braces = sros._indented_to_braces
get_sros_remediation = sros.get_sros_remediation


class TestBracesToIndented:
    def test_simple_config(self):
        config = 'configure {\n    router "Base" {\n        bgp {\n            admin-state enable\n        }\n    }\n}'
        result = _braces_to_indented(config)
        expected = 'configure\n    router "Base"\n        bgp\n            admin-state enable'
        assert result == expected

    def test_empty_container(self):
        config = 'configure {\n    router "Base" {\n        bgp { }\n    }\n}'
        result = _braces_to_indented(config)
        expected = 'configure\n    router "Base"\n        bgp'
        assert result == expected

    def test_comments_stripped(self):
        config = '# Generated by Nokia\n# TiMOS\nconfigure {\n    system {\n        name "r1"\n    }\n}'
        result = _braces_to_indented(config)
        assert result == 'configure\n    system\n        name "r1"'

    def test_empty_input(self):
        assert _braces_to_indented("") == ""
        assert _braces_to_indented("\n\n") == ""


class TestIndentedToBraces:
    def test_simple_hierarchy(self):
        indented = "configure\n  router \"Base\"\n    bgp\n      admin-state enable"
        result = _indented_to_braces(indented)
        assert 'configure {' in result
        assert 'router "Base" {' in result
        assert "bgp {" in result
        assert "admin-state enable" in result
        assert result.count("{") == result.count("}")

    def test_leaf_only(self):
        indented = "admin-state enable"
        result = _indented_to_braces(indented)
        assert result == "admin-state enable"

    def test_empty_input(self):
        assert _indented_to_braces("") == ""


class TestSrosRemediation:
    def test_add_interface(self):
        running = 'configure {\n    router "Base" {\n    }\n}'
        intended = (
            'configure {\n    router "Base" {\n        interface "new" {\n'
            "            admin-state enable\n        }\n    }\n}"
        )
        result = get_sros_remediation("test-device", running, intended)
        assert 'interface "new"' in result
        assert "admin-state enable" in result
        assert "delete" not in result

    def test_delete_interface(self):
        running = (
            'configure {\n    router "Base" {\n        interface "old" {\n'
            "            admin-state enable\n        }\n    }\n}"
        )
        intended = 'configure {\n    router "Base" {\n    }\n}'
        result = get_sros_remediation("test-device", running, intended)
        assert "delete" in result
        assert '"old"' in result

    def test_modify_value(self):
        running = 'configure {\n    router "Base" {\n        bgp {\n            connect-retry 120\n        }\n    }\n}'
        intended = (
            'configure {\n    router "Base" {\n        bgp {\n            connect-retry 90\n        }\n    }\n}'
        )
        result = get_sros_remediation("test-device", running, intended)
        assert "connect-retry 90" in result

    def test_no_diff(self):
        config = (
            'configure {\n    router "Base" {\n        bgp {\n            admin-state enable\n        }\n    }\n}'
        )
        result = get_sros_remediation("test-device", config, config)
        assert result == ""

    def test_add_and_delete_ordering(self):
        """Verify that additions appear before deletions in the output."""
        running = (
            'configure {\n    router "Base" {\n        interface "old-if" {\n'
            "            admin-state enable\n            port 1/1/1\n        }\n    }\n}"
        )
        intended = (
            'configure {\n    router "Base" {\n        interface "new-if" {\n'
            "            admin-state enable\n            port 1/1/2\n        }\n    }\n}"
        )
        result = get_sros_remediation("test-device", running, intended)
        add_pos = result.find('interface "new-if"')
        delete_pos = result.find("delete")
        assert add_pos < delete_pos, "Additions should appear before deletions"

    def test_deep_hierarchy(self):
        """Test deeply nested SROS config (service > vprn > interface > sap)."""
        running = (
            "configure {\n    service {\n"
            '        vprn "customer-a" {\n'
            "            service-id 100\n"
            '            interface "to-pe" {\n'
            "                sap 1/1/1:100 {\n"
            "                    ingress {\n"
            "                        qos 10\n"
            "                    }\n"
            "                }\n"
            "            }\n"
            "        }\n"
            "    }\n"
            "}"
        )
        intended = (
            "configure {\n    service {\n"
            '        vprn "customer-a" {\n'
            "            service-id 100\n"
            '            interface "to-pe" {\n'
            "                sap 1/1/1:100 {\n"
            "                    ingress {\n"
            "                        qos 20\n"
            "                    }\n"
            "                    egress {\n"
            "                        qos 30\n"
            "                    }\n"
            "                }\n"
            "            }\n"
            "        }\n"
            "    }\n"
            "}"
        )
        result = get_sros_remediation("test-device", running, intended)
        assert "qos 20" in result
        assert "qos 30" in result
        assert "egress" in result
        assert result.count("{") == result.count("}")

    def test_comment_stripping(self):
        """Configs with comments should be handled correctly."""
        running = (
            "# Generated by Nokia\n# TiMOS-B-24.7.R1\n"
            'configure {\n    system {\n        name "router1"\n    }\n}'
        )
        intended = (
            "# Generated by Nokia\n# TiMOS-B-24.7.R1\n"
            'configure {\n    system {\n        name "router2"\n    }\n}'
        )
        result = get_sros_remediation("test-device", running, intended)
        assert 'name "router2"' in result
        assert "Generated" not in result
        assert "TiMOS" not in result

    def test_add_only_no_deletes(self):
        """Adding new config without removing anything should produce no delete commands."""
        running = (
            'configure {\n    router "Base" {\n        bgp {\n'
            "            admin-state enable\n        }\n    }\n}"
        )
        intended = (
            'configure {\n    router "Base" {\n        bgp {\n'
            "            admin-state enable\n"
            "            connect-retry 90\n"
            '            group "peers" {\n'
            "                peer-as 65001\n"
            "            }\n"
            "        }\n    }\n}"
        )
        result = get_sros_remediation("test-device", running, intended)
        assert "connect-retry 90" in result
        assert 'group "peers"' in result
        assert "peer-as 65001" in result
        assert "delete" not in result

    def test_output_is_valid_mdcli(self):
        """Generated output must be wrapped in configure { ... } with balanced braces."""
        running = (
            'configure {\n    router "Base" {\n        bgp {\n            connect-retry 120\n        }\n    }\n}'
        )
        intended = (
            'configure {\n    router "Base" {\n        bgp {\n            connect-retry 90\n        }\n    }\n}'
        )
        result = get_sros_remediation("test-device", running, intended)
        assert result.startswith("configure {")
        assert result.count("{") == result.count("}")

    def test_deterministic_output(self):
        """Same inputs should always produce the same output."""
        running = (
            'configure {\n    router "Base" {\n        bgp {\n            connect-retry 120\n        }\n    }\n}'
        )
        intended = (
            'configure {\n    router "Base" {\n        bgp {\n            connect-retry 90\n        }\n    }\n}'
        )
        result1 = get_sros_remediation("test-device", running, intended)
        result2 = get_sros_remediation("test-device", running, intended)
        assert result1 == result2

    def test_empty_configs_no_error(self):
        """Empty configs should return empty string without error."""
        result = get_sros_remediation("test-device", "", "")
        assert result == ""


class TestSrosFixtures:
    """Tests using representative SROS configuration fixture files."""

    FIXTURES = Path(__file__).parent / "fixtures" / "sros"

    def test_fixture_patch_matches_expected(self):
        """Verify patch generation against stored expected output."""
        running = (self.FIXTURES / "running_config.txt").read_text()
        intended = (self.FIXTURES / "intended_config.txt").read_text()
        expected_patch = (self.FIXTURES / "expected_patch.txt").read_text().strip()

        result = get_sros_remediation("pe-router-01", running, intended)
        assert result == expected_patch

    def test_fixture_patch_is_valid_mdcli(self):
        """Verify fixture patch output is valid hierarchical MD-CLI."""
        running = (self.FIXTURES / "running_config.txt").read_text()
        intended = (self.FIXTURES / "intended_config.txt").read_text()

        result = get_sros_remediation("pe-router-01", running, intended)
        assert result.startswith("configure {")
        assert result.count("{") == result.count("}")

    def test_fixture_patch_contains_expected_changes(self):
        """Verify patch contains all expected remediation changes."""
        running = (self.FIXTURES / "running_config.txt").read_text()
        intended = (self.FIXTURES / "intended_config.txt").read_text()

        result = get_sros_remediation("pe-router-01", running, intended)

        # Modified values
        assert "connect-retry 90" in result
        assert 'description "Transit Provider B"' in result

        # New neighbor added
        assert 'neighbor "192.168.2.1"' in result

        # Interface replacement
        assert 'interface "to-core-2"' in result
        assert 'delete interface "to-core-1"' in result

        # QoS changes in service VPRN
        assert "qos 20" in result
