name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        python: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Setup dev env
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python -m pip install -r requirements/dev.txt
      - name: Run ruff format
        run: ruff format .
      - name: Run ruff
        run: ruff .

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        netbox_version: ["v3.6.9", "v3.7.8", "v4.0.7"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build NetBox
        run: cd development && docker compose build --build-arg NETBOX_VERSION=${{ matrix.netbox_version }}
      - name: Run tests
        run: cd development && docker compose run netbox sh -c "cd /plugin/netbox_config_diff && pytest"
