name: Commit

on: [push, pull_request]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 10
      matrix:
        os: [ubuntu-latest]
        version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up python ${{ matrix.version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - name: Setup dev env
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python -m pip install -r requirements/dev.txt
      - name: Run black
        run: black --check --diff --color .
      - name: Run ruff
        run: ruff netbox_config_diff