name: Publish

on:
  release:
    types: [created]

jobs:
  deploy:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Setup publish env
        run: |
            python -m pip install --upgrade pip
            python -m pip install setuptools wheel build twine
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
        run: |
          python -m build
          python -m twine upload dist/*
